import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-gradient-to-b from-white to-slate-50 text-slate-900">
          {children}
          <footer className="text-muted-foreground mt-16 border-t border-slate-100 bg-transparent py-8 text-center text-sm">
            © {new Date().getFullYear()} Universidade — Todos os direitos reservados
          </footer>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
